chore: license-file introduced in metadata version 2.4, not 2.1
Upload to pypi failed:

```
Uploading kelvin_rest_api_client-2.4.2-py3-none-any.whl (22.8KiB)
error: Failed to publish `dist/kelvin_rest_api_client-2.4.2-py3-none-any.whl` to https://test.pypi.org/legacy/
 Caused by: Server returned status code 400 Bad Request. Server says: 400 license-file introduced in metadata version 2.4,
not 2.1. See https://packaging.python.org/specifications/core-metadata for more information.
```

https://github.com/astral-sh/uv/issues/9513#issuecomment-2519527822

This is needed for python 3.7 support. A new setuptools version should
fix it in the future.

Issue univention/dev/internal/dev-issues/dev-incidents#204