chore: Filename 'kelvin-rest-api-client-2.4.2.tar.gz' is invalid, should be 'kelvin_rest_api_client-2.4.2.tar.gz'
```
Successfully built dist/kelvin-rest-api-client-2.4.2.tar.gz
Successfully built dist/kelvin_rest_api_client-2.4.2-py3-none-any.whl
ls -l dist
total 76
-rw-rw-r-- 1 jbroders jbroders 53157 Mar 30 17:26 kelvin-rest-api-client-2.4.2.tar.gz
-rw-rw-r-- 1 jbroders jbroders 22494 Mar 30 17:26 kelvin_rest_api_client-2.4.2-py3-none-any.whl
uv publish --username __token__ --index testpypi
Publishing 2 files to https://test.pypi.org/legacy/
Uploading kelvin_rest_api_client-2.4.2-py3-none-any.whl (22.0KiB)
warning: `kelvin-rest-api-client-2.4.2.tar.gz` has a non-normalized filename (expected `kelvin_rest_api_client-2.4.2.tar.gz`). Pass `--preview-features publish-require-normalized` to skip such files.
Uploading kelvin_rest_api_client-2.4.2.tar.gz (51.9KiB)
error: Failed to publish `dist/kelvin-rest-api-client-2.4.2.tar.gz` to https://test.pypi.org/legacy/
  Caused by: Server returned status code 400 Bad Request. Server says: 400 Filename 'kelvin-rest-api-client-2.4.2.tar.gz' is invalid, should be 'kelvin_rest_api_client-2.4.2.tar.gz'.
make: *** [Makefile:140: release-test] Error 2
```

Issue univention/dev/internal/dev-issues/dev-incidents#204